# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mainApp


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(213, 219, 255);")
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 150, 331, 217))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")

        self.loginEdit = QtWidgets.QLineEdit(self.widget)

        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)

        self.loginEdit.setFont(font)
        self.loginEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.loginEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.loginEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginEdit.setText("")
        self.loginEdit.setFrame(False)
        self.loginEdit.setObjectName("loginEdit")

        self.verticalLayout.addWidget(self.loginEdit)

        self.passwordEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordEdit.setText("")
        self.passwordEdit.setFrame(False)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout.addWidget(self.passwordEdit)

        self.forgotButton = QtWidgets.QPushButton(self.widget)
        self.forgotButton.setCheckable(False)
        self.forgotButton.setFlat(True)
        self.forgotButton.setObjectName("forgotButton")
        self.forgotButton.clicked.connect(self.forgot_password)
        self.verticalLayout.addWidget(self.forgotButton)

        self.enterbutton = QtWidgets.QPushButton(self.widget)

        font = QtGui.QFont()
        font.setPointSize(12)

        self.enterbutton.setFont(font)
        self.enterbutton.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.enterbutton.setFlat(False)
        self.enterbutton.setObjectName("enterbutton")
        self.verticalLayout.addWidget(self.enterbutton)

        self.info_label = QtWidgets.QLabel(self.widget)
        font.setPointSize(10)
        self.info_label.setFont(font)
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginEdit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.passwordEdit.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.forgotButton.setText(_translate("MainWindow", "Забыли пароль?"))
        self.enterbutton.setText(_translate("MainWindow", "Войти"))

    def forgot_password(self):
        print("Мы выслали письмо с инструкциями на вашу почту!")




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
