# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 631))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")

        self.profile = QtWidgets.QWidget()
        self.profile.setEnabled(True)
        self.profile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.profile.setMouseTracking(False)
        self.profile.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.profile.setAccessibleName("")
        self.profile.setObjectName("profile")
        self.tabWidget.addTab(self.profile, "")

        self.class_decr = QtWidgets.QWidget()
        self.class_decr.setObjectName("class_descr")

        self.tableWidget = QtWidgets.QTableWidget(self.class_decr)
        self.tableWidget.setGeometry(QtCore.QRect(40, 110, 711, 411))
        self.tableWidget.setObjectName("tableWidget")
        colCount = 5
        self.tableWidget.setColumnCount(colCount)
        self.tableWidget.setHorizontalHeaderLabels(["Фамилия", "Имя", "Отчество", "Дата рождения", "Телефон"])
        self.tableWidget.setRowCount(0)
        rowPos = self.tableWidget.rowCount()
        info = ["Гайдомак", "Мария", "Олеговна", "13-08-2002", "89050342142"]
        self.add_row(rowPos, info)

        self.add_pupil = QtWidgets.QPushButton(self.class_decr)
        self.add_pupil.setGeometry(QtCore.QRect(40, 60, 161, 31))
        self.add_pupil.setObjectName("add_pupil")
        self.add_pupil.clicked.connect(self.add_new_row)

        self.refresh = QtWidgets.QPushButton(self.class_decr)
        self.refresh.setGeometry(QtCore.QRect(220, 60, 161, 31))
        self.refresh.setObjectName("refresh")
        self.refresh.clicked.connect(lambda: self.save_row(colCount = 5))

        self.info_about_class_label = QtWidgets.QLabel(self.class_decr)
        self.info_about_class_label.setGeometry(QtCore.QRect(41, 20, 161, 31))
        self.info_about_class_label.setObjectName("info_about_class_label")
        self.info_about_class_label.setText("Класс: 7б")

        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)

        self.info_about_class_label.setFont(font)

        self.tabWidget.addTab(self.class_decr, "")

        self.document = QtWidgets.QWidget()
        self.document.setObjectName("document")
        self.tabWidget.addTab(self.document, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile), _translate("MainWindow", "Профиль"))
        self.add_pupil.setText(_translate("MainWindow", "Добавить ученика"))
        self.refresh.setText(_translate("MainWindow", "Сохранить изменения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.class_decr), _translate("MainWindow", "Класс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.document), _translate("MainWindow", "Отчёт"))

    def add_row(self, current_row, info):
        self.tableWidget.insertRow(current_row)
        for e, i in enumerate(info):
            item = QtWidgets.QTableWidgetItem(i)
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(current_row, e, item)
        self.tableWidget.resizeColumnsToContents()

    def add_new_row(self):
        current_row = self.tableWidget.rowCount()
        self.tableWidget.insertRow(current_row)

    def save_row(self, colCount):
        current_row = self.tableWidget.rowCount()
        for i in range(0, current_row):
            print(current_row)
            for l in range(colCount):
                if isinstance(self.tableWidget.item(i,l), QtWidgets.QTableWidgetItem):
                    print(self.tableWidget.item(i, l).text())
                    self.tableWidget.item(i, l).setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.resizeColumnsToContents()



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
